### ISSUE TITLE
dom_node does not work on native components

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#110]
_From @catmando on December 22, 2015 20:55_

i.e. if you use ref to get the id of say a "div" then you can't say ref["my_div"].dom_node as you would expect.

``` ruby
class Foo < React::Component::Base
  after_mount do
    refs[:my_div].dom_node # is nil!
  end
  def render
    div(ref: :my_div) { "no can do" }
  end
end
```

seems like the ref is pointing some ruby object which is just a simple wrapper around the native object... not sure how to solve.

For now work around is to do this:

``` ruby
`React.findDOMNode(#{refs[:my_div].to_n})` # === refs[:my_div].dom_node
```

_Copied from original issue: zetachang/react.rb#110_

**Comment by catmando** [comment]
@zetachang - this may also have been fixed

**Comment by zetachang** [comment]
It's fixed, test is added.

Some notes here, the current behavior is: 
- `refs[:my_div]` will give you a component instance
- `a_component.dom_node` will give you the actual DOM node without wrapping.

**Comment by catmando** [comment]
so does this work:  `Element[a_component.dom_node].html` (for example)

I wonder if we should make Element[a_component] just automatically apply .dom_node

so you say `Element[a_component]`  (nice ?)
