### ISSUE TITLE
should_update? passing in native objects and expecting native true false return

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#113]
_From @catmando on January 4, 2016 22:24_

should_update? passes two native object hashes (for new params, and new state) and only works properly if true or false are returned (i.e. nil does not work as false)

This all work aroundable, but a nuisance... Luckily should_update? is not used that frequently.  At least lets update the documentation

_Copied from original issue: zetachang/react.rb#113_

**Comment by catmando** [comment]
@zetachang - a lot of this got rewritten, this may in fact not be an issue any more not sure.

**Comment by janbiedermann** [comment]
i believe this is a gone issue
