### ISSUE TITLE
Deprecate React.addons.classSet

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#12]
_From @zetachang on March 15, 2015 6:7_

This is deprecated in 0.13.0 and could be implemented easily in Ruby.

http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
http://facebook.github.io/react/docs/class-name-manipulation.html

_Copied from original issue: zetachang/react.rb#12_

**Comment by catmando** [comment]
@zetachang - it would be nice to have something like this, perhaps its a separate gem?

**Comment by janbiedermann** [comment]
this is long gone, so it seems.
