### ISSUE TITLE
Remove opal-browser dependency

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#133]
_From @wied03 on March 25, 2016 21:13_

In order to keep the core GEM light, might want to see if this can be removed and if necessary, put it on a higher level GEM.

_Copied from original issue: zetachang/react.rb#133_

**Comment by sollycatprint** [comment]
_From @ajjahn on March 28, 2016 14:28_

@wied03 I agree with this. Opal browser is only gaining the ability to [attach components to browser Elements](https://github.com/zetachang/react.rb/blob/master/lib/react/top_level.rb#L89-L95). Really, we could continue to support that, but remove the requirement. Users can add depend on opal-browser specifically if they want that behavior.

**Comment by catmando** [comment]
@zetachang see if you can figure this out... the problem I have with any of this is the trade off of making things easy for entry level people, while satisfying those that are trying to keep things focused and low payload

**Comment by zetachang** [comment]
Done in e82a1362

The good news is that we are not actually using any `opal-browser` stuff, the referred `Element` is a `opal-jquery` element.
