### ISSUE TITLE
Customize rendered layout

### ISSUE THREAD

**Issue by rdlh** [ruby-hyperloop/hyper-react#148]
### Hey guys!

We're using a `resolve_layout` function in our `ApplicationController`, but your gem doesn't allow to change the layout ([`application` by default](https://github.com/reactrb/reactrb/blob/7471ceb74c245646e259ff2a31727da63be42158/lib/reactive-ruby/rails/controller_helper.rb#L9))

**It would be awesome being able for us to customize the rendered layout.**

`app/controllers/application_controller.rb`

``` rb
class ApplicationController < ActionController::Base
  layout :resolve_layout

  def resolve_layout
    if something?
      'foo'
    else
      'bar'
    end
  end
end
```

**Comment by catmando** [comment]
Excellent point!  I'm declaring it a "bug" so we can get this fixed in the next point release (coming soon!)

**Comment by catmando** [comment]
Layout can be specified like this:

`render_component {}, layout: 'my_layout'`

Note that the full syntax is: `render_component "Name", component-params, options` so to access the options you have to at least supply an empty component-params hash. 

For example just doing `render_component layout: 'my_layout'` would be interpreted as sending the layout param to your component.
