### ISSUE TITLE
feature request: more helpful error message when calling a component without the ()

### ISSUE THREAD

**Issue by hayley** [ruby-hyperloop/hyper-react#152]
As a beginner, I was totally stumped by the following and it would be helpful if the following situation:

``` ruby
# incorrect:
Element['#songlist'].render { SongList }
# correct:
Element['#songlist'].render { SongList() }
```

produced an error more helpful than the one that appears to be built into react.js:
`RuntimeError: a components render method must generate and return exactly 1 element or a string`

Thanks!

**Comment by catmando** [comment]
I think @hayley is correct, and hopefully its possible to do something like this:

`RuntimeError: a components render method must generate and return exactly 1 element or a string. Did you mean 'SongList()' ?`

Its just a matter of having heuristic checks for the more obvious ooops cases... anybody have an issue with this?
