### ISSUE TITLE
Deep param compare should be the default

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#156]
when checking params for changes we should use deep comparisons of the params.

Because the ruby equality test is dependent on the class this works nicely.

So for example arrays and hashes will get a deep comparison by default.

But if you are using some kind of immutable object, then the comparison will be done by object_id.

For now we will deprecate the behavior, and allow the 0.9 behavior to be installed by requiring reactrb/deep-comparison

**Comment by catmando** [comment]
verify closed

**Comment by janbiedermann** [comment]
with lap20 its established that comparing opal ruby things with a js shallow compare is useless, js shallow compare would need to know opal ruby object internals to come even close to be useful.
This would add a lot of js code. Opal does that nicely. therefore should_component_update? now simple uses `next_params != current_params`, which is a deep compare.
Opal being smart here, will exit as soon as possible, in most cases this is very fast.
It also works for all opal ruby objects, as much as they are comparable in this way.
It also works for js types, should they be in the params, as longs as opal knows them.
It does not work if param is a js functions, for example, or a js object that opal cant handle in !=.
It is recommended for speed anyway, to use simple types as params.
