### ISSUE TITLE
NativeLibrary is not importing bare functions

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#162]
For example you should be able to define this:

``` javascript
SomeLib = {
  Fun1: function(props) {
    return React.createElement(
      "div",
      null,
      "Hello "
    )
  }
}
```

and then in ruby write:

``` ruby
class MyComponent < React::Component::Base
  def render 
    SomeLib::Fun1()
  end
end
```

Unfortunately NativeLibrary is not handling the case of simple functions.

Fix is about like this:

``` ruby
module React
  class NativeLibrary
    class << self
      def create_component_wrapper(klass, native_name, ruby_name)
        if React::API.native_react_component?(native_name)
          new_klass = klass.const_set ruby_name, Class.new
          new_klass.class_eval do
            include React::Component
            imports native_name
          end
          new_klass
# ADD THIS HERE
        elsif (native_fn = get_native_fn(native_name))
          klass.class_eval do
           define_method ruby_name do |*args |
             `#{native_fn}.call(...some value of self... but what?..., #{args})`
           end
        end
      end
  end
end
```

Not sure of the best way to determine if a string points to a native fn.

Also not sure what should be passed as first param to call... probably `this` will work?

**Comment by fkchang** [comment]
This will be important as this style is being advocated as preferred for stateless components. This was observed in reactstrap, where all the container components, ButtonGroup, ButtonToolbar, etc. are all implemented as stateless functional components (https://facebook.github.io/react/docs/reusable-components.html#stateless-functions).  For example https://github.com/reactstrap/reactstrap/blob/master/src/ButtonGroup.js

**Comment by scalp42** [comment]
@fkchang or @zetachang is there a way to see a gist of what it would like with just a ButtonGroup for example ?

Thanks in advance 😄

**Comment by zetachang** [comment]
Hi @scalp42 , you could check out a demo project I just set up https://github.com/zetachang/hype-react-bootstrap-example.

To use a native reactjs component, just use `imports` inside a `React::Component::Base` will work.

```ruby
class Button < React::Component::Base
  imports "Reactstrap.Button"
end

class ButtonGroup < React::Component::Base
  imports "Reactstrap.ButtonGroup"
end


class Foo < React::Component::Base
  def render
    ButtonGroup() {
      Button { "Left" }
      Button { "Middle" }
      Button { "Right"}
    }
  end
end
```

**Comment by scalp42** [comment]
@zetachang really great example, it's very appreciated! Thanks a lot! 🙇
