### ISSUE TITLE
Including opal-jquery with reactrb breaks

### ISSUE THREAD

**Issue by bwl21** [ruby-hyperloop/hyper-react#166]
I have an app which already includes opal-jquery. It appears that there is a conflict.

I have created a test case - https://github.com/bwl21/reactrb-jquery-confict

this is my require tree in application.rb

``` ruby
require 'opal'
require 'opal-jquery'

require 'react-latest'     # or other version i.e. react-v14
#require 'reactrb'; require 'clock'

require 'controller'

puts "now starting testcase"
puts
```

This is my Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.1.0)
    concurrent-ruby (1.0.0)
    graphviz (0.1.0)
    hike (1.2.3)
    method_source (0.8.2)
    opal (0.9.0)
      hike (~> 1.2)
      sourcemap (~> 0.1.0)
      sprockets (~> 3.1)
      tilt (>= 1.4)
    opal-activesupport (0.3.0)
      opal (>= 0.5.0, < 1.0.0)
    opal-browser (0.2.0)
      opal
      paggio
    opal-jquery (0.4.1)
      opal (>= 0.7.0, < 0.10.0)
    paggio (0.2.6)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.4)
    rake (10.4.2)
    reactrb (0.8.8)
      opal (>= 0.8.0)
      opal-activesupport (>= 0.2.0)
      opal-browser (= 0.2.0)
    sass (3.4.20)
    slop (3.6.0)
    sourcemap (0.1.1)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    tilt (2.0.1)
    vector2d (2.1.0)
    zip (2.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  bundler
  graphviz
  opal (~> 0.9.0)
  opal-jquery (~> 0.4.0)
  pry
  rake
  reactrb
  sass
  vector2d (~> 2.1.0)
  zip

```

**Comment by zetachang** [comment]
By using an non-minified jQuery, there is an exception raised

```
jquery-3.1.1.js:3855 Uncaught TypeError: selector.$respond_to? is not a function
```

Looks like we accidentally mess up with the opal-jquery `Element#find` method in our code base (around https://github.com/reactrb/reactrb/blob/0-8-stable/lib/react/top_level.rb#L76).

**Comment by zetachang** [comment]
So until we fix this, the current workaround is to prevent using `Element#render` on jQuery element and **also** load **opal-jquery** after **reactrb**.

I create a patch as a fix to the example repo you provide. https://gist.github.com/zetachang/3c31c8f52f2f4d68dc7166a6be1306bf

**Comment by zetachang** [comment]
The fix is landed on master. The reason why `$window#on` breaks is that it attempts to pass the plain JS `window` to `Element#find` and we try to do a ruby `respond_to?` check on it.

**Comment by bwl21** [comment]
I cloned this repository
bundle install
bundle rake exec install

I updated my gemfile accordingly to use reactrb 0.9.0

restarted the testcase and it works Thanks a lot.
