### ISSUE TITLE
Make react-rails default way to load reactjs

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#169]
Current approach got some drawback
- reactjs is no longer a single bundle now, there are "react.js" & "react-dom.js"
- We need to ship new gem as new reactjs version released thus `react-latest` could make sense.

So the proposed approach will be delegating the actual source management to [react-rails](https://github.com/reactjs/react-rails) which is kept up to date as newer version of react released. 

It would be a one line require in your opal code

``` ruby
require "react/react-source" # must before "reactrb" require
require "reactrb"
```

Deprecation warning for all the required source from **source** folder will be shown properly suggesting which version of react-rails they should installed according to https://github.com/reactjs/react-rails/blob/master/VERSIONS.md, and we don't lock on specific version of react-rails, so a fresh install will always use the latest version of reactjs.

**Comment by catmando** [comment]
I thought I did fix this???

**Comment by zetachang** [comment]
So there is two parts of this issue:
- Stop shipping reactrb with reactjs sources start with deprecation msgs in `react-latest.js`, `react-vXX.js`
- Make `react-rails` a runtime dependency, so user only need to require `react/react-source` if they want to opt-in without adding another line in Gemfile.
- Wrap "react-rails" path setup to `react/react-source` given that the [current usage suggestion](https://github.com/reactrb/reactrb/blob/master/lib/reactrb.rb#L5) of react-rails only work on Rails environment.

**Comment by catmando** [comment]
okay, but I thought the first part was done?  Is that right?  I cant remember :-)

**Comment by zetachang** [comment]
Seems like no, we only provide warning if user haven't got reactjs setup currently.

**Comment by catmando** [comment]
okay so we don't provide any react.js file?

**Comment by zetachang** [comment]
We still provide reactjs source by using the copy from react-rails.

Mitch VanDuyn notifications@github.com 於 2016年10月7日週五 上午11:57 寫道：

**Comment by zetachang** [comment]
I will send a PR for the [installation page](https://github.com/reactrb/reactrb.github.io/blob/source/source/installation.html.md) on the doc site before making next release. @barriehadfield is there any doc I missed requires update?

@catmando  Does reactrb-rails-generator or any other gems need update too ?

**Comment by catmando** [comment]
@loicboutet - can you see if @zetachang's PR effects the generator (I am thinking not, as the generator will just pull the latest version, but perhaps we should test?)

**Comment by barriehadfield** [comment]
@zetachang you are right, that is the only page that will need to be updated. Depending on what you do, I might need to change the showcase tutorial but I will handle that after your PR. Please message me in Gitter when you are ready as I miss Github mentions.

**Comment by zetachang** [comment]
So as this is released in 0-9, I am going to close it.
