### ISSUE TITLE
Element#render re-mounts instead of re-rerenders

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#170]
``` ruby
every(1) do
  Element['#id].render do
    Hello(time: Time.now)
  end
end
```

Hello will be mounted over and over again.  This is because a new temporary class is created each time Element#render is called, and react does not see the two render cycles as being for the same component because the class is now different.

Following code fixes:

``` ruby

      Element.instance_eval do
        `window.React.hyper_act_components = {}`
        define_method :react_component do
          component = `window.React.hyper_act_components[self]`
          if `typeof component === "undefined"`
            component = Class.new(React::Component::Base)
            component.class_eval do
              def needs_update?(*args)
                true
              end
            end
            `window.React.hyper_act_components[self] = #{component}`
          end
          component
        end
        define_method :render do |container = nil, params = {}, &block|
          react_component.class_eval { render(container, params, &block) }
          React.render(React.create_element(react_component), self)
        end
      end  if Object.const_defined?('Element')
```

This goes in react/top_level.rb near the bottom

Note the code is bit klunky because Element is just a native wrapper so we can't properly attach instance variables.  Nor does self seem to work normally.

**Comment by zetachang** [comment]
Another approach below would avoids temporary class created, _but_ require a more restricted API

``` ruby
Element.instance_eval do
  define_method :render do |container = nil, params = {}, &block|
    React.render(React.create_element(container, params, &block), self)
  end
end
```

## API Change

Previously you can do,

``` ruby
Element.new(:div).render { Foo(name: 'fred') }
```

but now,

``` ruby
Element.new(:div).render(Foo, name: 'fred')
```

Reason for this change is that the method_missing magic is only handled inside component instance, and yes we could definitely create a temporary render context to make this work, but I still think less is more as to this kind of syntax sugar.

Also, this is more aligned to the original `React.render` API.

**Comment by catmando** [comment]
hmmm...

There is now a render callback (you can still just do a def render, but there are advantages to using the callback, it follows rails convention similar to default_scope)

So the idea was to keep this 100% consistent.

**Comment by zetachang** [comment]
So I think the problem is that we could make it clearer by implement this on top level api instead of  opal-jquery extension,  like this

``` ruby
React.render_to(Element['#div'].to_n) { Hello(name: "jake") }
```

And make the jquery extension use this directly. Also, a different `render_to` will make it clear that user should provide only a param (target DOM) and a render block.

**Comment by catmando** [comment]
But why?  To me having a consist macro (render) that works the same regardless of context makes learning easy and delights the programmer.

It's worth a little under the hood magic.

**Comment by zetachang** [comment]
Sorry for not clarifying clearly, I am not proposing removal of jquery extension. What i mean is that we could move the implementation to core api and make the extension simply invoke the new `render_to` API.

**Comment by catmando** [comment]
ahhh yes... that is the absolutely correct solution.  I have refactored that stuff a couple of times, but it needs one more round I think.

**Comment by zetachang** [comment]
How about a fix like this

``` ruby
define_method :render do |container = nil, params = {}, &block|
    if `#{self.to_n}._reactrb_component_class === undefined`
      klass = Class.new(React::Component::Base)
      klass.class_eval do
        render(container, params, &block)
      end
      `#{self.to_n}._reactrb_component_class = #{klass}`
    end
    React.render(React.create_element(`#{self.to_n}._reactrb_component_class`), self)
 end
```

I've verified that the component will only mount once.

**Comment by zetachang** [comment]
Turns out that we only need to cache the class but override the render method every time, 

``` ruby
  define_method :render do |container = nil, params = {}, &block|
    if `#{self.to_n}._reactrb_component_class === undefined`
      `#{self.to_n}._reactrb_component_class = #{Class.new(React::Component::Base)}`
    end
    klass = `#{self.to_n}._reactrb_component_class`
    klass.class_eval do
      render(container, params, &block)
    end

    React.render(React.create_element(`#{self.to_n}._reactrb_component_class`), self)
  end
```

**Comment by catmando** [comment]
great!  I think functionally its the same as the original, but I couldn't figure out how to reliably attach the component class to self... yours is much simpilier!
