### ISSUE TITLE
params[:no_prerender] not work

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#173]
Passing `no_prerender=1` as URL params won't work as expected. Given that `params[:no_prerender]` return a `String`, thus it will set `prerender` to `false`. (See https://github.com/reactrb/reactrb/blob/master/lib/reactive-ruby/rails/controller_helper.rb#L11)

**Comment by zetachang** [comment]
I am wondering what's the convention on this, is `no_prerender=1` and `no_prerender=true` all supposed to work?

**Comment by catmando** [comment]
yeah its kind of ugly, but helps in debug... the intent is to give quick ability to shutdown prerendering.  no_prerender=...anyvalue... shuts off prerendering.

If you have a better plan great :-)

**Comment by zetachang** [comment]
Okay, so this is actually an intended feature. But isn't it weird that the end user could toggle the prerender option through url params by default? 

Maybe we could make this configurable through `render_component`, say

``` ruby
render_component "Index", {}, layout: :explicit_layout, prerender: false
```

The default will be true to match the current behavior.

**Comment by catmando** [comment]
its a terrible feature thrown in for debug... we definitely need to figure out a better way

**Comment by janbiedermann** [comment]
params[:no_prerender] not work for sure, because i removed this feature in lap10 i believe.
Currently there is the global prerendering setting, or per component prerender param like react-rails does it.
