### ISSUE TITLE
no way to turn off deep/shallow compare warning

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#180]
latest release gives a deprecation warning about deep vs. shallow comparison.

But there is no specified way to turn the warning off!

The warning only comes up once, but perhaps we should have a module that you include that gets rid of the warning as well

**Comment by zetachang** [comment]
Could we check `Opal::VERSION` and require the correct `ShouldComponentUpdate` implementation?

**Comment by catmando** [comment]
no I don't think checking Opal::VERSION will help...

The problem is that in 0.9 all param changes were made with "deep comparision", in 0.10 we began using "shallow comparison" so the message is not exactly a deprecation message, but really a warning, that behavior has changed.

To go back to 0.9 behavior you have to  require "reactrb/deep-compare" (well actually is it hyper-react/deep-compare) which should turn off the message.

BUT the issue what if you want to get rid of the message and keep 'shallow-compare'  so we need to require 'reactrb/shallow-compare' which will implement the 0.10 behavior without the message. 

Does that make sense?

**Comment by zetachang** [comment]
Okay, so I understand `0.9` as Opal version previously .. but it's actually hyper-react version you are referring to. 

So now I am confused about the original intent to introduce the change. As #156 stated, we want to use `deep-compare` by default, so we introduced a migrate path by

1. Letting user to adopt the **new** behavior by requiring `react/deep-compare`
2. Show a deprecation warning if user is still using the old behavior

Am I understand this correctly?

**Comment by dan-klasson** [comment]
@catmando This is still an issue for me

**Comment by catmando** [comment]
@zetachang that is correct... @dan-klasson if you require react/deep-compare does the warning go away?

**Comment by catmando** [comment]
I will close this in a couple of days if @dan-klasson does not respond, or confirms that the require works.

**Comment by janbiedermann** [comment]
i believe this issue is no longer there.
