### ISSUE TITLE
Module for including params only works once

### ISSUE THREAD

**Issue by illogikal** [ruby-hyperloop/hyper-react#185]
Using: hyper-react 0.10.0, opal 0.9.4
When I try and modularize params like below for some components. This works if i include in one component.
```
class Bar
  include React::Component
  include OtherModule
  include DefaultParams
  render(:div) do
    params.foo
  end
end
module DefaultParams
  def DefaultParams.included(mod)
    mod.send :param, :foo, type: String, default: :bar
  end
end
```
But if I include in 2, it does not.
```
class Bar
  include React::Component
  include OtherModule
  include DefaultParams
  render(:div) do
    params.foo
  end
end
class Baz
  include React::Component
  include OtherModule
  include DefaultParams
  render(:div) do
    params.foo
  end
end
module DefaultParams
  def DefaultParams.included(mod)
    mod.send :param, :foo, type: String, default: :bar
  end
end
```
Which causes this error in console: 
```
kernel.rb:1052
Uncaught $NameError {name: "DefaultParams", message: "uninitialized constant Object::DefaultParams", stack: "↵    at SingletonClass_alloc.$new (http://localhos…00/assets/corelib/runtime.self.js?body=1:1767:17)"}
```
The OtherModule is a set of app wide constants but no functional code.

**Comment by catmando** [comment]
good use case... I'm on vacation but maybe @zetachang can have a look... I must say the error seems bizarre!!!

**Comment by zetachang** [comment]
Maybe `DefaultParams` need to be initialized before defining class `Bar` & `Baz`?

**Comment by illogikal** [comment]
What would be best practices for doing that? Calling from the top level component?

**Comment by zetachang** [comment]
What I mean is to put this part
```ruby
module DefaultParams
  def DefaultParams.included(mod)
    mod.send :param, :foo, type: String, default: :bar
  end
end
```
at the top of your file or require if first before all component subclass get loaded.

**Comment by illogikal** [comment]
Ah, the issue was actually unrelated. I was using reactrb auto-import, but I didn't do a 
require './components/default_form_params' before trying to use this file in multiple places. On the plus side this now works nicely :)
