### ISSUE TITLE
React.render should return ruby instance or actual DOM instance

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#187]
Below is how we currently handle the top level render

```ruby
 def self.render(element, container)
    container = `container.$$class ? container[0] : container`
    component = Native(`ReactDOM.render(#{element.to_n}, container, function(){#{yield if block_given?}})`)
    component.class.include(React::Component::API)
    component
  end
```

Which is different from what ReactJS's semantic [1]

> Render a React element into the DOM in the supplied container and return a reference to the component (or returns null for stateless components).

The current approach by returning a `Native` is just a workaround, so we will fix this by returning:

* the actual ruby instance if your are render a custom component
* the actual DOM node if you are render a dom component

[1] https://facebook.github.io/react/docs/react-dom.html#render

**Comment by catmando** [comment]
again, if its a breaking change best to do a warning (using the deprecation warning method) which includes instructions to require the appropriate file which will implement the new semantics.
