### ISSUE TITLE
actual DOM & ruby instance should be attached as ref

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#188]
Currently,  ref callback is invoked with the native react instance. This is not ideal since the native instance should always be hidden to prevent abstraction leakage.

So we will fix the ref behavior by attach
* actual DOM node if the ref is specified on DOM component
* actual Ruby instance if the ref is specified on a React::Component powered custom component
* old strings refs (e.g. `ref="my_div"`) will remain the same.

For more details on how ref work , see https://facebook.github.io/react/docs/refs-and-the-dom.html.

**Comment by catmando** [comment]
Okay buts it going to be a breaking change.  I think we will have to display warning, and to get rid of warning by requiring a file that implements the new feature

**Comment by zetachang** [comment]
Yeah, will do that which is a safer way to move on.

**Comment by zetachang** [comment]
[Update] Decide to leave the string refs behavior remain the same given that it is already a deprecated (or about to be deprecated) API by facebook.

**Comment by janbiedermann** [comment]
string refs dont work, but otherwise its like in the opening post, thats why i close this.
