### ISSUE TITLE
Deprecation after building example app by manuals

### ISSUE THREAD

**Issue by noma4i** [ruby-hyperloop/hyper-react#190]
```
Deprecated feature used in React::Component. Using shallow incoming params comparison.
Do a require "reactrb/deep-compare, to get 0.9 behavior
```

This came up after Iv done step-by-step example app with hyper-mesh

I can see double reactjs call as well:

```
Navigated to http://localhost:3000/
Download the React DevTools for a better development experience: https://fb.me/react-devtools react.self.js?body=1:180 
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-server.self.js?body=1:18
```

**Comment by catmando** [comment]
@zetachang - I sure don't see why this is happening, but it does appear that react is getting included twice!

**Comment by noma4i** [comment]
BTW. After switching to react using webpack double init gone

**Comment by zetachang** [comment]
The deprecation warning might be misleading, some of the discussion on this is at #180. 

Also, another problem is that the correct file to get rid of the warning is actually `hyper-react/deep-compare` instead of `reactrb/deep-compare`.

**Comment by catmando** [comment]
Issue #180 already addresses the one issue, and I raised a second issue for the double include of react.js
