### ISSUE TITLE
turn off all console noise in production

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#193]
We probably want to do this via the logging methods in  isomorphic base, warning and info should be turned off in production.

**Comment by zetachang** [comment]
I am thinking of introducing a new environment variable `HYPER_REACT_ENV` which will be set as `RAILS_ENV` if used as rails plugin. And if not used with Rails, user need to set it manually.

**Comment by catmando** [comment]
sure 

somebody else also suggested introducing a config file
