### ISSUE TITLE
react.js appears to be loaded twice

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#194]
I can't figure out how or why, but its true...

**Comment by zetachang** [comment]
The cause of this is that we currently ship `react` & `react-server` in our default setup (using `react-rails`), and each of them has its own copy of ReactDOM. 

This issue will be fixed when #186 is done.

**Comment by zetachang** [comment]
This is fixed in master, by requiring `react/react-source-browser` will ensure only one copy of ReactDOM is loaded.
