### ISSUE TITLE
Drop ruby 1.9.3 support

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#201]
Given that 
* Opal is already depending on ruby version `>= 2.0` on master (https://github.com/opal/opal/commit/5990ac3b463ec6b58cadb3f03f0d35933653bb52)
* Support for ruby 1.9.3 has already ended about 1 year. https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

So in the next release of hyper-react, it will require ruby `>= 2.0`.

**Comment by catmando** [comment]
Agreed.

**Comment by janbiedermann** [comment]
1.0.0-lap18 is tested and targeted with and for ruby 2.4.3 and ruby 2.5.0
