### ISSUE TITLE
Migrate to React.Component

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#208]
Currently we are using `React.createClass` to create a bridge object holding reference to actual ruby instance.

But upon React 15.5, [`React.createClass` will be deprecated](https://github.com/facebook/react/issues/8854). Even though a separate package will be extracted, but I think it's time for us to move on using ES6 class.

/cc @fkchang

**Comment by janbiedermann** [comment]
done in the laps
