### ISSUE TITLE
Opal 0.11 support

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyper-react#222]
You may not want to start this until Opal 0.11 is actually released but this issue will be ready.

I tried to use Opal 0.11 like so, as we use the safe navigation operator from Ruby 2.4 which Opal 0.11 adds.

```ruby
gem "hyperloop"
gem "opal", "~> 0.11.0.rc1", github: "opal/opal"
gem "opal-sprockets", github: "opal/opal-sprockets"
gem "opal-rails", github: "opal/opal-rails"
```

hyper-react gives this error when trying to load a component (which works on earlier versions of Opal):

```
 Error: Cannot find component: 'React.TopLevelRailsComponent'. Make sure your component is globally available to render.
```

**Comment by janbiedermann** [comment]
opal 0.11 -pre has been failing in many ways
opal 0.11 final is expected dec 08, reevaluate then again, until now 0.10.5 is recommended

**Comment by sfcgeorge** [comment]
Opal 0.11 is now released :)

**Comment by janbiedermann** [comment]
done in 1.0.0 lap18

```
source https://gems.ruby-hyperloop.org

gem "opal", git: "https://github.com/janbiedermann/opal.git", branch: "master"
gem "opal-activesupport", git: "https://github.com/janbiedermann/opal-activesupport.git", branch: "master"
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem "opal-rails", git: "https://github.com/opal/opal-rails.git", branch: "master"

gem 'hyperloop', '1.0.0-lap18'
gem 'hyper-spec', '1.0.0-lap18'
```

note: there are still terrible security issues, not recommended for production use

**Comment by zw963** [comment]
so cool.will try it tomorrow
