### ISSUE TITLE
Q: Are models only working with ActiveRecord or with any other ORM/ODM?

### ISSUE THREAD

**Issue by 34code** [ruby-hyperloop/hyper-react#229]
I'm evaluating this for a project with a different ODM so wondering if it will work OOB..

**Comment by janbiedermann** [comment]
you could wrap all accesses to nobrainer/rethinkdb other ODB in Server Operations and from those dispatch messages accordingly to connected clients. But that is surely not as comfortable as just using the Hyperloop provided Hyper Model.

**Comment by 34code** [comment]
True. Any way to NOT require Hyper Model by default? I'm using the latest webpacker gem and the current documentation is leading to some roadblocks :|

**Comment by catmando** [comment]
closed, and opened issue on documentation to make this more clear.
