### ISSUE TITLE
Use mini-racer instead of ruby-racer

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#230]

**Comment by janbiedermann** [comment]
done in sachsenring

**Comment by trammel** [comment]
It's done in https://github.com/janbiedermann/hyper-react/tree/sachsenring but that hasn't hit master yet... are there plans to do a merge?

**Comment by janbiedermann** [comment]
yes, already done, its in edge and 1.0.0-lap28

**Comment by janbiedermann** [comment]
lap28 is based on edge, edge will become master later on
