### ISSUE TITLE
Opal links point to online casino website for opal.org domain

### ISSUE THREAD

**Issue by iongion** [ruby-hyperloop/hyper-react#264]
The https://opalrb.org should point to https://opalrb.com
You can find the issue on this page http://ruby-hyperloop.org/docs/components/docs/
How is it even allowed to have *rapware under a `.org` TLD ?!?
![image](https://user-images.githubusercontent.com/867609/39758349-e0e73ad2-52cf-11e8-923e-b3f9bf9154a8.png)
Now you get this
![image](https://user-images.githubusercontent.com/867609/39758421-1633bf76-52d0-11e8-841a-61b3b5429ebf.png)

**Comment by catmando** [comment]
thanks... doc site is being redone... thanks for reporting

**Comment by barriehadfield** [comment]
Wow - thanks for reporting that, I wonder how that happened!
