### ISSUE TITLE
Add Value Link Helpers

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#37]
_From @wied03 on May 22, 2015 21:23_

Just makes it a little easier to use valueLink

_Copied from original issue: zetachang/react.rb/pull/37_

**Comment by wied03** [comment]
@sollycatprint - I would say this is important but I thought I read that value_link is going away with React anyways.

**Comment by catmando** [comment]
@zetachang can you investigate... not sure what value link is...

**Comment by zetachang** [comment]
I would suggest we should not integrate feature already deprecated. As the doc said

> ReactLink is deprecated as of React v15. The recommendation is to explicitly set the value and change handler, instead of using ReactLink.

Maybe we could close it?

**Comment by catmando** [comment]
I'm fine with closing as long as @wied03 agrees

**Comment by wied03** [comment]
I'm fine with closing (see earlier comment).
